### ISSUE TITLE
Be on the Powered by Faust page ?

### ISSUE THREAD

**Issue by sletz** [TobiasKozel/GuitarD#17]
Would you be interested to be on the [Powered By Faust page ?](https://faust.grame.fr/community/made-with-faust/). How stable is the project ?

**Comment by TobiasKozel** [comment]
Hi, I'd be interested in featuring this project on the Faust Page.

The DSP part of it is fairly stable and reliable thanks to most of it being Faust generated code.
The UI side is something I've been meaning to work on for a while now to make the project more stable and approachable from a user perspective. 
But even in the current state, it's functional enough even though not exactly pretty.

Thank you for reaching out!

**Comment by sletz** [comment]
Thanks, added [here](https://faust.grame.fr/community/made-with-faust/#guitard). Feel free to provide more complete informations on the project !
